"""initial core data model

Revision ID: 809cac63fb15
Revises: 
Create Date: 2026-09-05 10:56:55.594399
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '809cac63fb15'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.Enum('bronze', 'silver', 'gold', name='customer_tier', native_enum=False, length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('billing_address', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_customers_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('code', name=op.f('uq_customers_code'))
    )
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_created_by'), 'customers', ['created_by'], unique=False)
    op.create_index(op.f('ix_customers_is_active'), 'customers', ['is_active'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_tier'), 'customers', ['tier'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_permissions_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_permissions_created_by'), 'permissions', ['created_by'], unique=False)
    op.create_table('price_lists',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('customer_tier', sa.Enum('bronze', 'silver', 'gold', name='price_list_customer_tier', native_enum=False, length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_price_lists_valid_period_ordered')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_price_lists_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_lists')),
    sa.UniqueConstraint('code', name=op.f('uq_price_lists_code'))
    )
    op.create_index(op.f('ix_price_lists_created_at'), 'price_lists', ['created_at'], unique=False)
    op.create_index(op.f('ix_price_lists_created_by'), 'price_lists', ['created_by'], unique=False)
    op.create_index(op.f('ix_price_lists_customer_tier'), 'price_lists', ['customer_tier'], unique=False)
    op.create_index(op.f('ix_price_lists_is_active'), 'price_lists', ['is_active'], unique=False)
    op.create_table('product_categories',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_product_categories_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_product_categories_code'))
    )
    op.create_index(op.f('ix_product_categories_created_at'), 'product_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_categories_created_by'), 'product_categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_product_categories_is_active'), 'product_categories', ['is_active'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.Enum('admin', 'sales_manager', 'sales_rep', 'finance_ops', 'customer', name='role_code', native_enum=False, length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_roles_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_created_by'), 'roles', ['created_by'], unique=False)
    op.create_table('sales_teams',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sales_teams_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_sales_teams_manager_id_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_sales_teams_name'))
    )
    op.create_index(op.f('ix_sales_teams_created_at'), 'sales_teams', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_teams_created_by'), 'sales_teams', ['created_by'], unique=False)
    op.create_index(op.f('ix_sales_teams_is_active'), 'sales_teams', ['is_active'], unique=False)
    op.create_index(op.f('ix_sales_teams_manager_id'), 'sales_teams', ['manager_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('billing_interval', sa.Enum('monthly', 'quarterly', 'yearly', name='billing_interval', native_enum=False, length=40), nullable=False),
    sa.Column('interval_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('proration_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('refund_policy', sa.Enum('none', 'prorated', 'full', name='refund_policy', native_enum=False, length=40), server_default='prorated', nullable=False),
    sa.Column('cancellation_notice_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cancellation_notice_days >= 0', name=op.f('ck_subscription_plans_cancellation_notice_non_negative')),
    sa.CheckConstraint('interval_count >= 1', name=op.f('ck_subscription_plans_interval_count_positive')),
    sa.CheckConstraint('unit_amount >= 0', name=op.f('ck_subscription_plans_unit_amount_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_subscription_plans_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_subscription_plans_code'))
    )
    op.create_index(op.f('ix_subscription_plans_created_at'), 'subscription_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_plans_created_by'), 'subscription_plans', ['created_by'], unique=False)
    op.create_index(op.f('ix_subscription_plans_is_active'), 'subscription_plans', ['is_active'], unique=False)
    op.create_table('warehouses',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('shipping_cost_weight', sa.Numeric(precision=8, scale=2), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('shipping_cost_weight >= 0', name=op.f('ck_warehouses_shipping_cost_weight_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_warehouses_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouses_code'))
    )
    op.create_index(op.f('ix_warehouses_created_at'), 'warehouses', ['created_at'], unique=False)
    op.create_index(op.f('ix_warehouses_created_by'), 'warehouses', ['created_by'], unique=False)
    op.create_index(op.f('ix_warehouses_is_active'), 'warehouses', ['is_active'], unique=False)
    op.create_table('approval_chains',
    sa.Column('min_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('required_role_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_score IS NULL OR max_score > min_score', name=op.f('ck_approval_chains_score_band_ordered')),
    sa.CheckConstraint('min_score >= 0', name=op.f('ck_approval_chains_min_score_non_negative')),
    sa.CheckConstraint('step_order >= 1', name=op.f('ck_approval_chains_step_order_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_approval_chains_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['required_role_id'], ['roles.id'], name=op.f('fk_approval_chains_required_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_chains')),
    sa.UniqueConstraint('min_score', 'step_order', name='uq_approval_chains_min_score_step')
    )
    op.create_index(op.f('ix_approval_chains_created_at'), 'approval_chains', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_chains_created_by'), 'approval_chains', ['created_by'], unique=False)
    op.create_index(op.f('ix_approval_chains_is_active'), 'approval_chains', ['is_active'], unique=False)
    op.create_index('ix_approval_chains_min_score_max_score', 'approval_chains', ['min_score', 'max_score'], unique=False)
    op.create_index(op.f('ix_approval_chains_required_role_id'), 'approval_chains', ['required_role_id'], unique=False)
    op.create_table('discount_tiers',
    sa.Column('customer_tier', sa.Enum('bronze', 'silver', 'gold', name='discount_tier_customer_tier', native_enum=False, length=40), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('max_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_discount_percent >= 0 AND max_discount_percent <= 100', name=op.f('ck_discount_tiers_max_discount_percentage_range')),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_discount_tiers_category_id_product_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_discount_tiers_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount_tiers')),
    sa.UniqueConstraint('customer_tier', 'category_id', name='uq_discount_tiers_tier_category')
    )
    op.create_index(op.f('ix_discount_tiers_category_id'), 'discount_tiers', ['category_id'], unique=False)
    op.create_index(op.f('ix_discount_tiers_created_at'), 'discount_tiers', ['created_at'], unique=False)
    op.create_index(op.f('ix_discount_tiers_created_by'), 'discount_tiers', ['created_by'], unique=False)
    op.create_index(op.f('ix_discount_tiers_is_active'), 'discount_tiers', ['is_active'], unique=False)
    op.create_table('products',
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='unit', nullable=False),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('item_type', sa.Enum('one_time', 'subscription', name='product_item_type', native_enum=False, length=40), server_default='one_time', nullable=False),
    sa.Column('is_promoted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cost_price >= 0', name=op.f('ck_products_cost_price_non_negative')),
    sa.CheckConstraint('list_price >= 0', name=op.f('ck_products_list_price_non_negative')),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name=op.f('ck_products_tax_rate_percentage_range')),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_products_category_id_product_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_products_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku'))
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_created_by'), 'products', ['created_by'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_item_type'), 'products', ['item_type'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('sales_team_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_users_customer_id_customers'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_team_id'], ['sales_teams.id'], name=op.f('fk_users_sales_team_id_sales_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_index(op.f('ix_users_customer_id'), 'users', ['customer_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index('ix_users_role_id_is_active', 'users', ['role_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_sales_team_id'), 'users', ['sales_team_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index('ix_audit_logs_resource_resource_id', 'audit_logs', ['resource', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_user_id_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('price_list_items',
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=12, scale=3), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_quantity > 0', name=op.f('ck_price_list_items_min_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_price_list_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_price_list_items_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], name=op.f('fk_price_list_items_price_list_id_price_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_list_items_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_list_items')),
    sa.UniqueConstraint('price_list_id', 'product_id', 'min_quantity', name='uq_price_list_items_list_product_qty')
    )
    op.create_index(op.f('ix_price_list_items_created_at'), 'price_list_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_price_list_items_created_by'), 'price_list_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_price_list_items_price_list_id'), 'price_list_items', ['price_list_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_product_id'), 'price_list_items', ['product_id'], unique=False)
    op.create_index('ix_price_list_items_product_id_price_list_id', 'price_list_items', ['product_id', 'price_list_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(length=60), nullable=False),
    sa.Column('attribute_value', sa.String(length=60), nullable=False),
    sa.Column('sku_suffix', sa.String(length=30), nullable=True),
    sa.Column('extra_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_product_variants_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('product_id', 'attribute_name', 'attribute_value', name='uq_product_variants_product_attribute')
    )
    op.create_index(op.f('ix_product_variants_created_at'), 'product_variants', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_variants_created_by'), 'product_variants', ['created_by'], unique=False)
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('quotations',
    sa.Column('quote_number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'sent', 'under_negotiation', 'confirmed', 'fulfilled', 'cancelled', name='quotation_status', native_enum=False, length=40), server_default='draft', nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('margin_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('blended_risk_score', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('max_line_excess', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('requires_finance_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blended_risk_score >= 0', name=op.f('ck_quotations_blended_risk_score_non_negative')),
    sa.CheckConstraint('max_line_excess >= 0', name=op.f('ck_quotations_max_line_excess_non_negative')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_quotations_total_amount_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_quotations_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_quotations_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_quotations_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotations')),
    sa.UniqueConstraint('quote_number', name=op.f('uq_quotations_quote_number'))
    )
    op.create_index(op.f('ix_quotations_created_at'), 'quotations', ['created_at'], unique=False)
    op.create_index(op.f('ix_quotations_created_by'), 'quotations', ['created_by'], unique=False)
    op.create_index(op.f('ix_quotations_customer_id'), 'quotations', ['customer_id'], unique=False)
    op.create_index('ix_quotations_customer_id_status', 'quotations', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_quotations_last_activity_at'), 'quotations', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_quotations_owner_id'), 'quotations', ['owner_id'], unique=False)
    op.create_index('ix_quotations_owner_id_status', 'quotations', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_index('ix_quotations_status_created_at', 'quotations', ['status', 'created_at'], unique=False)
    op.create_table('upsell_rules',
    sa.Column('trigger_product_id', sa.Integer(), nullable=False),
    sa.Column('suggested_product_id', sa.Integer(), nullable=False),
    sa.Column('co_purchase_score', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('min_margin_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('co_purchase_score >= 0', name=op.f('ck_upsell_rules_co_purchase_score_non_negative')),
    sa.CheckConstraint('min_margin_percent >= 0 AND min_margin_percent <= 100', name=op.f('ck_upsell_rules_min_margin_percentage_range')),
    sa.CheckConstraint('trigger_product_id <> suggested_product_id', name=op.f('ck_upsell_rules_trigger_differs_from_suggested')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_upsell_rules_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['suggested_product_id'], ['products.id'], name=op.f('fk_upsell_rules_suggested_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_product_id'], ['products.id'], name=op.f('fk_upsell_rules_trigger_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upsell_rules')),
    sa.UniqueConstraint('trigger_product_id', 'suggested_product_id', name='uq_upsell_rules_trigger_suggested')
    )
    op.create_index(op.f('ix_upsell_rules_created_at'), 'upsell_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_upsell_rules_created_by'), 'upsell_rules', ['created_by'], unique=False)
    op.create_index(op.f('ix_upsell_rules_is_active'), 'upsell_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_upsell_rules_suggested_product_id'), 'upsell_rules', ['suggested_product_id'], unique=False)
    op.create_index(op.f('ix_upsell_rules_trigger_product_id'), 'upsell_rules', ['trigger_product_id'], unique=False)
    op.create_index('ix_upsell_rules_trigger_score', 'upsell_rules', ['trigger_product_id', 'co_purchase_score'], unique=False)
    op.create_table('approval_requests',
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('blended_risk_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_line_excess', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('triggered_by_line_gate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'returned_for_revision', name='approval_request_status', native_enum=False, length=40), server_default='pending', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blended_risk_score >= 0', name=op.f('ck_approval_requests_request_score_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_approval_requests_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_approval_requests_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_created_at'), 'approval_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_created_by'), 'approval_requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_approval_requests_quotation_id'), 'approval_requests', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index('ix_approval_requests_status_requested_at', 'approval_requests', ['status', 'requested_at'], unique=False)
    op.create_table('deal_health_snapshots',
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_stalled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('days_inactive', sa.Integer(), server_default='0', nullable=False),
    sa.Column('has_discount_anomaly', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('discount_vs_rep_average', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('has_delivery_slippage', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('days_slipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days_inactive >= 0', name=op.f('ck_deal_health_snapshots_days_inactive_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_deal_health_snapshots_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_deal_health_snapshots_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_health_snapshots'))
    )
    op.create_index('ix_deal_health_snapshots_alerts', 'deal_health_snapshots', ['is_stalled', 'has_discount_anomaly', 'has_delivery_slippage'], unique=False)
    op.create_index(op.f('ix_deal_health_snapshots_created_at'), 'deal_health_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_deal_health_snapshots_created_by'), 'deal_health_snapshots', ['created_by'], unique=False)
    op.create_index(op.f('ix_deal_health_snapshots_quotation_id'), 'deal_health_snapshots', ['quotation_id'], unique=False)
    op.create_index('ix_deal_health_snapshots_quotation_snapshot', 'deal_health_snapshots', ['quotation_id', 'snapshot_at'], unique=False)
    op.create_index(op.f('ix_deal_health_snapshots_snapshot_at'), 'deal_health_snapshots', ['snapshot_at'], unique=False)
    op.create_table('fulfillments',
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'partially_fulfilled', 'fulfilled', 'backordered', name='fulfillment_status', native_enum=False, length=40), server_default='pending', nullable=False),
    sa.Column('shipment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_shipping_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('estimated_shipping_cost >= 0', name=op.f('ck_fulfillments_estimated_shipping_cost_non_negative')),
    sa.CheckConstraint('shipment_count >= 0', name=op.f('ck_fulfillments_shipment_count_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_fulfillments_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_fulfillments_quotation_id_quotations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fulfillments'))
    )
    op.create_index(op.f('ix_fulfillments_created_at'), 'fulfillments', ['created_at'], unique=False)
    op.create_index(op.f('ix_fulfillments_created_by'), 'fulfillments', ['created_by'], unique=False)
    op.create_index(op.f('ix_fulfillments_quotation_id'), 'fulfillments', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_fulfillments_status'), 'fulfillments', ['status'], unique=False)
    op.create_table('quotation_lines',
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_list_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('allowed_discount_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('line_excess_points', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('line_discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('line_tax_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('line_type', sa.Enum('one_time', 'subscription', name='quotation_line_item_type', native_enum=False, length=40), server_default='one_time', nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('added_from_upsell', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(line_type = 'subscription' AND subscription_plan_id IS NOT NULL) OR (line_type = 'one_time' AND subscription_plan_id IS NULL)", name=op.f('ck_quotation_lines_subscription_line_requires_plan')),
    sa.CheckConstraint('allowed_discount_percent >= 0 AND allowed_discount_percent <= 100', name=op.f('ck_quotation_lines_allowed_discount_percentage_range')),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name=op.f('ck_quotation_lines_discount_percentage_range')),
    sa.CheckConstraint('line_excess_points >= 0', name=op.f('ck_quotation_lines_line_excess_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_quotation_lines_quantity_positive')),
    sa.CheckConstraint('unit_cost_price >= 0', name=op.f('ck_quotation_lines_unit_cost_price_non_negative')),
    sa.CheckConstraint('unit_list_price >= 0', name=op.f('ck_quotation_lines_unit_list_price_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_quotation_lines_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_quotation_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_lines_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name=op.f('fk_quotation_lines_subscription_plan_id_subscription_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_quotation_lines_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_lines')),
    sa.UniqueConstraint('quotation_id', 'line_number', name='uq_quotation_lines_quotation_line_no')
    )
    op.create_index(op.f('ix_quotation_lines_created_at'), 'quotation_lines', ['created_at'], unique=False)
    op.create_index(op.f('ix_quotation_lines_created_by'), 'quotation_lines', ['created_by'], unique=False)
    op.create_index(op.f('ix_quotation_lines_line_type'), 'quotation_lines', ['line_type'], unique=False)
    op.create_index(op.f('ix_quotation_lines_product_id'), 'quotation_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_quotation_lines_quotation_id'), 'quotation_lines', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_quotation_lines_subscription_plan_id'), 'quotation_lines', ['subscription_plan_id'], unique=False)
    op.create_index(op.f('ix_quotation_lines_variant_id'), 'quotation_lines', ['variant_id'], unique=False)
    op.create_table('stock_levels',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name=op.f('ck_stock_levels_quantity_on_hand_non_negative')),
    sa.CheckConstraint('quantity_reserved <= quantity_on_hand', name=op.f('ck_stock_levels_reserved_within_on_hand')),
    sa.CheckConstraint('quantity_reserved >= 0', name=op.f('ck_stock_levels_quantity_reserved_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_levels_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_levels_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_stock_levels_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_levels_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_levels'))
    )
    op.create_index(op.f('ix_stock_levels_created_at'), 'stock_levels', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_levels_created_by'), 'stock_levels', ['created_by'], unique=False)
    op.create_index(op.f('ix_stock_levels_product_id'), 'stock_levels', ['product_id'], unique=False)
    op.create_index('ix_stock_levels_product_id_warehouse_id', 'stock_levels', ['product_id', 'warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_levels_variant_id'), 'stock_levels', ['variant_id'], unique=False)
    op.create_index(op.f('ix_stock_levels_warehouse_id'), 'stock_levels', ['warehouse_id'], unique=False)
    op.create_index('uq_stock_levels_warehouse_product_variant', 'stock_levels', ['warehouse_id', 'product_id', 'variant_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('approval_steps',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('required_role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'returned_for_revision', name='approval_step_status', native_enum=False, length=40), server_default='pending', nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'pending' AND actor_id IS NULL AND decided_at IS NULL) OR (status <> 'pending' AND actor_id IS NOT NULL AND decided_at IS NOT NULL)", name=op.f('ck_approval_steps_decided_step_has_actor_and_timestamp')),
    sa.CheckConstraint('step_order >= 1', name=op.f('ck_approval_steps_step_order_positive')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_approval_steps_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_approval_steps_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('fk_approval_steps_request_id_approval_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['required_role_id'], ['roles.id'], name=op.f('fk_approval_steps_required_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_steps')),
    sa.UniqueConstraint('request_id', 'step_order', name='uq_approval_steps_request_step')
    )
    op.create_index(op.f('ix_approval_steps_actor_id'), 'approval_steps', ['actor_id'], unique=False)
    op.create_index(op.f('ix_approval_steps_created_at'), 'approval_steps', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_steps_created_by'), 'approval_steps', ['created_by'], unique=False)
    op.create_index(op.f('ix_approval_steps_request_id'), 'approval_steps', ['request_id'], unique=False)
    op.create_index(op.f('ix_approval_steps_required_role_id'), 'approval_steps', ['required_role_id'], unique=False)
    op.create_index(op.f('ix_approval_steps_status'), 'approval_steps', ['status'], unique=False)
    op.create_table('backorders',
    sa.Column('fulfillment_id', sa.Integer(), nullable=False),
    sa.Column('quotation_line_id', sa.Integer(), nullable=False),
    sa.Column('quantity_outstanding', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.Enum('open', 'consolidated', 'fulfilled', 'cancelled', name='backorder_status', native_enum=False, length=40), server_default='open', nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_outstanding > 0', name=op.f('ck_backorders_backorder_quantity_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_backorders_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['fulfillment_id'], ['fulfillments.id'], name=op.f('fk_backorders_fulfillment_id_fulfillments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], name=op.f('fk_backorders_quotation_line_id_quotation_lines'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backorders'))
    )
    op.create_index(op.f('ix_backorders_created_at'), 'backorders', ['created_at'], unique=False)
    op.create_index(op.f('ix_backorders_created_by'), 'backorders', ['created_by'], unique=False)
    op.create_index(op.f('ix_backorders_fulfillment_id'), 'backorders', ['fulfillment_id'], unique=False)
    op.create_index(op.f('ix_backorders_quotation_line_id'), 'backorders', ['quotation_line_id'], unique=False)
    op.create_index(op.f('ix_backorders_status'), 'backorders', ['status'], unique=False)
    op.create_table('fulfillment_splits',
    sa.Column('fulfillment_id', sa.Integer(), nullable=False),
    sa.Column('quotation_line_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_fulfillment_splits_split_quantity_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_fulfillment_splits_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['fulfillment_id'], ['fulfillments.id'], name=op.f('fk_fulfillment_splits_fulfillment_id_fulfillments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], name=op.f('fk_fulfillment_splits_quotation_line_id_quotation_lines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_fulfillment_splits_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fulfillment_splits'))
    )
    op.create_index(op.f('ix_fulfillment_splits_created_at'), 'fulfillment_splits', ['created_at'], unique=False)
    op.create_index(op.f('ix_fulfillment_splits_created_by'), 'fulfillment_splits', ['created_by'], unique=False)
    op.create_index(op.f('ix_fulfillment_splits_fulfillment_id'), 'fulfillment_splits', ['fulfillment_id'], unique=False)
    op.create_index('ix_fulfillment_splits_line_warehouse', 'fulfillment_splits', ['quotation_line_id', 'warehouse_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_splits_quotation_line_id'), 'fulfillment_splits', ['quotation_line_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_splits_warehouse_id'), 'fulfillment_splits', ['warehouse_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('quotation_line_id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'modified', 'cancelled', name='subscription_status', native_enum=False, length=40), server_default='active', nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_cycle_start', sa.Date(), nullable=False),
    sa.Column('current_cycle_end', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_cycle_end > current_cycle_start', name=op.f('ck_subscriptions_cycle_dates_ordered')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_subscriptions_subscription_quantity_positive')),
    sa.CheckConstraint('unit_amount >= 0', name=op.f('ck_subscriptions_subscription_unit_amount_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_subscriptions_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_subscriptions_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], name=op.f('fk_subscriptions_quotation_line_id_quotation_lines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name=op.f('fk_subscriptions_subscription_plan_id_subscription_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('quotation_line_id', name=op.f('uq_subscriptions_quotation_line_id'))
    )
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_created_by'), 'subscriptions', ['created_by'], unique=False)
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscription_plan_id'), 'subscriptions', ['subscription_plan_id'], unique=False)
    op.create_table('billing_schedules',
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.Enum('one_time', 'recurring', name='billing_schedule_type', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'invoiced', 'paid', 'cancelled', name='billing_schedule_status', native_enum=False, length=40), server_default='scheduled', nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cycle_start', sa.Date(), nullable=True),
    sa.Column('cycle_end', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(length=40), nullable=True),
    sa.Column('invoiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_credit_note', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(schedule_type = 'recurring' AND subscription_id IS NOT NULL) OR (schedule_type = 'one_time' AND subscription_id IS NULL)", name=op.f('ck_billing_schedules_recurring_schedule_requires_subscription')),
    sa.CheckConstraint('(cycle_start IS NULL AND cycle_end IS NULL) OR (cycle_start IS NOT NULL AND cycle_end IS NOT NULL AND cycle_end >= cycle_start)', name=op.f('ck_billing_schedules_schedule_cycle_dates_consistent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_billing_schedules_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_billing_schedules_quotation_id_quotations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_billing_schedules_subscription_id_subscriptions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_schedules')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_billing_schedules_invoice_number'))
    )
    op.create_index(op.f('ix_billing_schedules_created_at'), 'billing_schedules', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_schedules_created_by'), 'billing_schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_billing_schedules_due_date'), 'billing_schedules', ['due_date'], unique=False)
    op.create_index(op.f('ix_billing_schedules_quotation_id'), 'billing_schedules', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_billing_schedules_schedule_type'), 'billing_schedules', ['schedule_type'], unique=False)
    op.create_index(op.f('ix_billing_schedules_status'), 'billing_schedules', ['status'], unique=False)
    op.create_index('ix_billing_schedules_status_due_date', 'billing_schedules', ['status', 'due_date'], unique=False)
    op.create_index(op.f('ix_billing_schedules_subscription_id'), 'billing_schedules', ['subscription_id'], unique=False)
    op.create_table('proration_records',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('cycle_start', sa.Date(), nullable=False),
    sa.Column('cycle_end', sa.Date(), nullable=False),
    sa.Column('cycle_days', sa.Integer(), nullable=False),
    sa.Column('remaining_days', sa.Integer(), nullable=False),
    sa.Column('old_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('new_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('old_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('charge_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('proration_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('change_date >= cycle_start AND change_date <= cycle_end', name=op.f('ck_proration_records_change_date_within_cycle')),
    sa.CheckConstraint('cycle_days > 0', name=op.f('ck_proration_records_cycle_days_positive')),
    sa.CheckConstraint('cycle_end > cycle_start', name=op.f('ck_proration_records_proration_cycle_dates_ordered')),
    sa.CheckConstraint('remaining_days >= 0 AND remaining_days <= cycle_days', name=op.f('ck_proration_records_remaining_days_within_cycle')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_proration_records_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_proration_records_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proration_records'))
    )
    op.create_index(op.f('ix_proration_records_created_at'), 'proration_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_proration_records_created_by'), 'proration_records', ['created_by'], unique=False)
    op.create_index(op.f('ix_proration_records_subscription_id'), 'proration_records', ['subscription_id'], unique=False)
    op.create_table('payments',
    sa.Column('billing_schedule_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.Enum('bank_transfer', 'card', 'cash', 'cheque', 'other', name='payment_method', native_enum=False, length=40), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_payment_amount_positive')),
    sa.ForeignKeyConstraint(['billing_schedule_id'], ['billing_schedules.id'], name=op.f('fk_payments_billing_schedule_id_billing_schedules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payments_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_billing_schedule_id'), 'payments', ['billing_schedule_id'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_created_by'), 'payments', ['created_by'], unique=False)
    # --- Deferred (use_alter) foreign keys -------------------------------
    # Added here by hand. Alembic autogenerate renders foreign keys inline
    # inside create_table and omits any marked use_alter=True, so without
    # this block created_by, users.customer_id and sales_teams.manager_id
    # would have no referential integrity at all. use_alter exists because
    # these FKs form cycles (users -> roles -> users, users -> customers ->
    # users) that cannot be satisfied by CREATE TABLE ordering alone.
    op.create_foreign_key(op.f('fk_approval_chains_created_by_users'), 'approval_chains', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_approval_requests_created_by_users'), 'approval_requests', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_approval_steps_created_by_users'), 'approval_steps', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_backorders_created_by_users'), 'backorders', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_billing_schedules_created_by_users'), 'billing_schedules', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_customers_created_by_users'), 'customers', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_deal_health_snapshots_created_by_users'), 'deal_health_snapshots', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_discount_tiers_created_by_users'), 'discount_tiers', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_fulfillment_splits_created_by_users'), 'fulfillment_splits', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_fulfillments_created_by_users'), 'fulfillments', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_payments_created_by_users'), 'payments', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_permissions_created_by_users'), 'permissions', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_price_list_items_created_by_users'), 'price_list_items', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_price_lists_created_by_users'), 'price_lists', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_product_categories_created_by_users'), 'product_categories', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_product_variants_created_by_users'), 'product_variants', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_products_created_by_users'), 'products', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_proration_records_created_by_users'), 'proration_records', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_quotation_lines_created_by_users'), 'quotation_lines', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_quotations_created_by_users'), 'quotations', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_roles_created_by_users'), 'roles', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_sales_teams_manager_id_users'), 'sales_teams', 'users', ['manager_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_sales_teams_created_by_users'), 'sales_teams', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_stock_levels_created_by_users'), 'stock_levels', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_subscription_plans_created_by_users'), 'subscription_plans', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_subscriptions_created_by_users'), 'subscriptions', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_upsell_rules_created_by_users'), 'upsell_rules', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_users_created_by_users'), 'users', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_users_customer_id_customers'), 'users', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_warehouses_created_by_users'), 'warehouses', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Deferred FKs must be dropped before the tables, or DROP TABLE fails
    # on the still-referencing constraints.
    op.drop_constraint(op.f('fk_approval_chains_created_by_users'), 'approval_chains', type_='foreignkey')
    op.drop_constraint(op.f('fk_approval_requests_created_by_users'), 'approval_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_approval_steps_created_by_users'), 'approval_steps', type_='foreignkey')
    op.drop_constraint(op.f('fk_backorders_created_by_users'), 'backorders', type_='foreignkey')
    op.drop_constraint(op.f('fk_billing_schedules_created_by_users'), 'billing_schedules', type_='foreignkey')
    op.drop_constraint(op.f('fk_customers_created_by_users'), 'customers', type_='foreignkey')
    op.drop_constraint(op.f('fk_deal_health_snapshots_created_by_users'), 'deal_health_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('fk_discount_tiers_created_by_users'), 'discount_tiers', type_='foreignkey')
    op.drop_constraint(op.f('fk_fulfillment_splits_created_by_users'), 'fulfillment_splits', type_='foreignkey')
    op.drop_constraint(op.f('fk_fulfillments_created_by_users'), 'fulfillments', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_created_by_users'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_permissions_created_by_users'), 'permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_price_list_items_created_by_users'), 'price_list_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_price_lists_created_by_users'), 'price_lists', type_='foreignkey')
    op.drop_constraint(op.f('fk_product_categories_created_by_users'), 'product_categories', type_='foreignkey')
    op.drop_constraint(op.f('fk_product_variants_created_by_users'), 'product_variants', type_='foreignkey')
    op.drop_constraint(op.f('fk_products_created_by_users'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('fk_proration_records_created_by_users'), 'proration_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotation_lines_created_by_users'), 'quotation_lines', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotations_created_by_users'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('fk_roles_created_by_users'), 'roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_sales_teams_manager_id_users'), 'sales_teams', type_='foreignkey')
    op.drop_constraint(op.f('fk_sales_teams_created_by_users'), 'sales_teams', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_levels_created_by_users'), 'stock_levels', type_='foreignkey')
    op.drop_constraint(op.f('fk_subscription_plans_created_by_users'), 'subscription_plans', type_='foreignkey')
    op.drop_constraint(op.f('fk_subscriptions_created_by_users'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('fk_upsell_rules_created_by_users'), 'upsell_rules', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_created_by_users'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_customer_id_customers'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_warehouses_created_by_users'), 'warehouses', type_='foreignkey')
    op.drop_index(op.f('ix_payments_created_by'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_billing_schedule_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_proration_records_subscription_id'), table_name='proration_records')
    op.drop_index(op.f('ix_proration_records_created_by'), table_name='proration_records')
    op.drop_index(op.f('ix_proration_records_created_at'), table_name='proration_records')
    op.drop_table('proration_records')
    op.drop_index(op.f('ix_billing_schedules_subscription_id'), table_name='billing_schedules')
    op.drop_index('ix_billing_schedules_status_due_date', table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_status'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_schedule_type'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_quotation_id'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_due_date'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_created_by'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_created_at'), table_name='billing_schedules')
    op.drop_table('billing_schedules')
    op.drop_index(op.f('ix_subscriptions_subscription_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_by'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_fulfillment_splits_warehouse_id'), table_name='fulfillment_splits')
    op.drop_index(op.f('ix_fulfillment_splits_quotation_line_id'), table_name='fulfillment_splits')
    op.drop_index('ix_fulfillment_splits_line_warehouse', table_name='fulfillment_splits')
    op.drop_index(op.f('ix_fulfillment_splits_fulfillment_id'), table_name='fulfillment_splits')
    op.drop_index(op.f('ix_fulfillment_splits_created_by'), table_name='fulfillment_splits')
    op.drop_index(op.f('ix_fulfillment_splits_created_at'), table_name='fulfillment_splits')
    op.drop_table('fulfillment_splits')
    op.drop_index(op.f('ix_backorders_status'), table_name='backorders')
    op.drop_index(op.f('ix_backorders_quotation_line_id'), table_name='backorders')
    op.drop_index(op.f('ix_backorders_fulfillment_id'), table_name='backorders')
    op.drop_index(op.f('ix_backorders_created_by'), table_name='backorders')
    op.drop_index(op.f('ix_backorders_created_at'), table_name='backorders')
    op.drop_table('backorders')
    op.drop_index(op.f('ix_approval_steps_status'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_required_role_id'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_request_id'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_created_by'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_created_at'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_actor_id'), table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index('uq_stock_levels_warehouse_product_variant', table_name='stock_levels', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_stock_levels_warehouse_id'), table_name='stock_levels')
    op.drop_index(op.f('ix_stock_levels_variant_id'), table_name='stock_levels')
    op.drop_index('ix_stock_levels_product_id_warehouse_id', table_name='stock_levels')
    op.drop_index(op.f('ix_stock_levels_product_id'), table_name='stock_levels')
    op.drop_index(op.f('ix_stock_levels_created_by'), table_name='stock_levels')
    op.drop_index(op.f('ix_stock_levels_created_at'), table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_index(op.f('ix_quotation_lines_variant_id'), table_name='quotation_lines')
    op.drop_index(op.f('ix_quotation_lines_subscription_plan_id'), table_name='quotation_lines')
    op.drop_index(op.f('ix_quotation_lines_quotation_id'), table_name='quotation_lines')
    op.drop_index(op.f('ix_quotation_lines_product_id'), table_name='quotation_lines')
    op.drop_index(op.f('ix_quotation_lines_line_type'), table_name='quotation_lines')
    op.drop_index(op.f('ix_quotation_lines_created_by'), table_name='quotation_lines')
    op.drop_index(op.f('ix_quotation_lines_created_at'), table_name='quotation_lines')
    op.drop_table('quotation_lines')
    op.drop_index(op.f('ix_fulfillments_status'), table_name='fulfillments')
    op.drop_index(op.f('ix_fulfillments_quotation_id'), table_name='fulfillments')
    op.drop_index(op.f('ix_fulfillments_created_by'), table_name='fulfillments')
    op.drop_index(op.f('ix_fulfillments_created_at'), table_name='fulfillments')
    op.drop_table('fulfillments')
    op.drop_index(op.f('ix_deal_health_snapshots_snapshot_at'), table_name='deal_health_snapshots')
    op.drop_index('ix_deal_health_snapshots_quotation_snapshot', table_name='deal_health_snapshots')
    op.drop_index(op.f('ix_deal_health_snapshots_quotation_id'), table_name='deal_health_snapshots')
    op.drop_index(op.f('ix_deal_health_snapshots_created_by'), table_name='deal_health_snapshots')
    op.drop_index(op.f('ix_deal_health_snapshots_created_at'), table_name='deal_health_snapshots')
    op.drop_index('ix_deal_health_snapshots_alerts', table_name='deal_health_snapshots')
    op.drop_table('deal_health_snapshots')
    op.drop_index('ix_approval_requests_status_requested_at', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_quotation_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_created_by'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_created_at'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('ix_upsell_rules_trigger_score', table_name='upsell_rules')
    op.drop_index(op.f('ix_upsell_rules_trigger_product_id'), table_name='upsell_rules')
    op.drop_index(op.f('ix_upsell_rules_suggested_product_id'), table_name='upsell_rules')
    op.drop_index(op.f('ix_upsell_rules_is_active'), table_name='upsell_rules')
    op.drop_index(op.f('ix_upsell_rules_created_by'), table_name='upsell_rules')
    op.drop_index(op.f('ix_upsell_rules_created_at'), table_name='upsell_rules')
    op.drop_table('upsell_rules')
    op.drop_index('ix_quotations_status_created_at', table_name='quotations')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index('ix_quotations_owner_id_status', table_name='quotations')
    op.drop_index(op.f('ix_quotations_owner_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_last_activity_at'), table_name='quotations')
    op.drop_index('ix_quotations_customer_id_status', table_name='quotations')
    op.drop_index(op.f('ix_quotations_customer_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_created_by'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_created_at'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_created_by'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_created_at'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_price_list_items_product_id_price_list_id', table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_product_id'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_price_list_id'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_created_by'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_created_at'), table_name='price_list_items')
    op.drop_table('price_list_items')
    op.drop_index('ix_audit_logs_user_id_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_resource_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_sales_team_id'), table_name='users')
    op.drop_index('ix_users_role_id_is_active', table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_item_type'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_created_by'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_discount_tiers_is_active'), table_name='discount_tiers')
    op.drop_index(op.f('ix_discount_tiers_created_by'), table_name='discount_tiers')
    op.drop_index(op.f('ix_discount_tiers_created_at'), table_name='discount_tiers')
    op.drop_index(op.f('ix_discount_tiers_category_id'), table_name='discount_tiers')
    op.drop_table('discount_tiers')
    op.drop_index(op.f('ix_approval_chains_required_role_id'), table_name='approval_chains')
    op.drop_index('ix_approval_chains_min_score_max_score', table_name='approval_chains')
    op.drop_index(op.f('ix_approval_chains_is_active'), table_name='approval_chains')
    op.drop_index(op.f('ix_approval_chains_created_by'), table_name='approval_chains')
    op.drop_index(op.f('ix_approval_chains_created_at'), table_name='approval_chains')
    op.drop_table('approval_chains')
    op.drop_index(op.f('ix_warehouses_is_active'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_created_by'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_created_at'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_subscription_plans_is_active'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_created_by'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_created_at'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_sales_teams_manager_id'), table_name='sales_teams')
    op.drop_index(op.f('ix_sales_teams_is_active'), table_name='sales_teams')
    op.drop_index(op.f('ix_sales_teams_created_by'), table_name='sales_teams')
    op.drop_index(op.f('ix_sales_teams_created_at'), table_name='sales_teams')
    op.drop_table('sales_teams')
    op.drop_index(op.f('ix_roles_created_by'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_product_categories_is_active'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_created_by'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_created_at'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_price_lists_is_active'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_customer_tier'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_created_by'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_created_at'), table_name='price_lists')
    op.drop_table('price_lists')
    op.drop_index(op.f('ix_permissions_created_by'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_customers_tier'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_active'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_by'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
