"""add user invitations, nullable password hash

Revision ID: fe1ed27193e6
Revises: e6ed9a2f450c
Create Date: 2026-09-06 00:06:37.691691
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fe1ed27193e6'
down_revision: str | None = 'e6ed9a2f450c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invitations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], name=op.f('fk_user_invitations_invited_by_id_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_invitations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_invitations_token_hash'))
    )
    op.create_index(op.f('ix_user_invitations_created_at'), 'user_invitations', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_invitations_invited_by_id'), 'user_invitations', ['invited_by_id'], unique=False)
    op.create_index(op.f('ix_user_invitations_user_id'), 'user_invitations', ['user_id'], unique=False)
    op.create_index('ix_user_invitations_user_id_accepted_at', 'user_invitations', ['user_id', 'accepted_at'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_user_invitations_user_id_accepted_at', table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_user_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_invited_by_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_created_at'), table_name='user_invitations')
    op.drop_table('user_invitations')
    # ### end Alembic commands ###
